version: '3.5'

services:
  minetoursoft-backend:
    build: .
    container_name: bk-minetoursoft
    image: minetoursoft-backend
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - app-minetoursoft:/app
    networks:
      - external
      - internal

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  app-minetoursoft: